# Generated by Django 3.0.7 on 2020-06-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=20)),
                ('dtel', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('deid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('dename', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('hname', models.CharField(max_length=30)),
                ('hst_address', models.CharField(max_length=30)),
                ('hst_city', models.CharField(max_length=30)),
                ('hstate', models.CharField(max_length=20)),
                ('hzip', models.IntegerField()),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pfname', models.CharField(max_length=30)),
                ('plname', models.CharField(max_length=20)),
                ('pgender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unkown')], max_length=1)),
                ('pbd', models.DateTimeField()),
                ('prace', models.CharField(blank=True, choices=[('ASIAN', 'Asian'), ('HISPANIC', 'Hispanic'), ('LATINO', 'Latin American'), ('AFRICAN', 'African American'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('pstatus', models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Devoiced'), ('W', 'Widow or widower')], max_length=1)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='PatientTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateTimeField()),
                ('tfreq', models.BigIntegerField(default=0)),
                ('tstatus', models.CharField(blank=True, choices=[('S', 'Successful'), ('R', 'Repeat'), ('F', 'Failed')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'patient_treatment',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(db_column='UID', primary_key=True, serialize=False)),
                ('ufname', models.CharField(max_length=20)),
                ('ulname', models.CharField(max_length=20)),
                ('urole', models.CharField(max_length=20)),
                ('did', models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Department')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=50)),
                ('ttype', models.CharField(choices=[('PHARMA', 'Pharma'), ('PROCEDURE', 'Procedure'), ('SURGERY', 'Surgery')], max_length=10)),
                ('deid', models.ForeignKey(db_column='deid', on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Disease')),
            ],
            options={
                'db_table': 'treatment',
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('phid', models.AutoField(primary_key=True, serialize=False)),
                ('phfname', models.CharField(max_length=30)),
                ('phtel', models.CharField(max_length=13)),
                ('phspl', models.CharField(max_length=30)),
                ('hid', models.ForeignKey(db_column='hid', on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital')),
                ('patient', models.ManyToManyField(related_name='physician', through='hospital.PatientTreatment', to='hospital.Patient')),
                ('treatment', models.ManyToManyField(related_name='physician', through='hospital.PatientTreatment', to='hospital.Treatment')),
            ],
            options={
                'db_table': 'physician',
            },
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='phid',
            field=models.ForeignKey(db_column='phid', on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Physician'),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient'),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='tid',
            field=models.ForeignKey(db_column='tid', on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.Treatment'),
        ),
        migrations.AddField(
            model_name='department',
            name='hid',
            field=models.ForeignKey(db_column='hid', on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='patienttreatment',
            unique_together={('pid', 'phid', 'tid', 'tdate', 'tfreq')},
        ),
    ]
